import "./globals.css";
import type { Metadata } from "next";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import ThemeProvider from "@/theme";
import BaseThemeProvider from "@/theme/contexts/base-theme-provider";
import ResponsiveAppBar from "@/layouts/main";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BaseThemeProvider>
          <ThemeProvider>
            <ResponsiveAppBar></ResponsiveAppBar>
            {children}
            <footer className="footer">
              <div className="contact-info">
                <h2>Contact phone!</h2>
                <p>
                  <a href="tel:+81363879202">TEL +81 3-6387-9202</a>
                </p>
                <p>Operation:42 Tokyo students</p>
              </div>
              <div>
                {/* <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2622.9858411969153!2d2.3185009999999995!3d48.896606999999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fa9e73a1ef7%3A0x4e808812dd36a382!2s42!5e0!3m2!1sja!2sjp!4v1725548274758!5m2!1sja!2sjp"
                width="100%"
                height="600"
                loading="lazy"
                className="mapContainer"
              /> */}
              </div>
            </footer>
          </ThemeProvider>
        </BaseThemeProvider>
      </body>
    </html>
  );
}
