import './globals.css';
import type { Metadata } from 'next';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import ThemeProvider from '@/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider>
          <header className='bg-gray-700 text-gray-600 body-font'>
            <div className='flex items-center'>
              <a className='flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0'>
                <img
                  className='logo'
                  src='https://42tokyo.jp/static/images/logo/42.svg'
                  alt='42logo'
                ></img>
              </a>
            </div>
            <div className='container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center'>
              <nav className='md:ml-auto md:mr-auto flex items-center text-base justify-center'>
                <a
                  className='text-white font-bold text-4xl mr-5 hover:text-gray-900'
                  href={`/`}
                >
                  TOP
                </a>
                <a
                  className='text-white font-bold text-4xl mr-5 hover:text-gray-900'
                  href={`/user`}
                >
                  MEMBERS
                </a>
                <a
                  className='text-white font-bold text-4xl mr-5 hover:text-gray-900'
                  href={`/info`}
                >
                  INFORMATION
                </a>
                <a
                  className='text-white font-bold text-4xl mr-5 hover:text-gray-900'
                  href={`/contact`}
                >
                  CONTACT
                </a>
              </nav>
              {/* <button className='inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0'>
                Button
                <svg
                  fill='none'
                  stroke='currentColor'
                  stroke-linecap='round'
                  stroke-linejoin='round'
                  stroke-width='2'
                  className='w-4 h-4 ml-1'
                  viewBox='0 0 24 24'
                >
                  <path d='M5 12h14M12 5l7 7-7 7'></path>
                </svg>
              </button> */}
            </div>
          </header>
          {children}
          <footer className='footer'>
            <div className='contact-info'>
              <h2>Contact phone!</h2>
              <p>
                <a href='tel:+81363879202'>+81 3-6387-9202</a>
              </p>
              <p>Operation:42 Tokyo students</p>
            </div>
            <div>
              {/* <iframe
                src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12961.792590762123!2d139.67729118855812!3d35.690588000000005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018f3002dd8f339%3A0x21c5cb36a88710b2!2s42Tokyo!5e0!3m2!1sja!2sjp!4v1725548150647!5m2!1sja!2sjp'
                width='100%'
                height='600'
                loading='lazy'
                className='mapContainer'
              /> */}
              <iframe
                src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2622.9858411969153!2d2.3185009999999995!3d48.896606999999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fa9e73a1ef7%3A0x4e808812dd36a382!2s42!5e0!3m2!1sja!2sjp!4v1725548274758!5m2!1sja!2sjp'
                width='100%'
                height='600'
                loading='lazy'
                className='mapContainer'
              />
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
